before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/ringo-is-a-color/heteroglossia/util/cli.version={{.Version}}
archives:
  - files:
      - none*
checksum:
  name_template: 'sha256sums.txt'
